# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CSVToolUIV2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("QPushButton{\n"
"background-color: #ffffb3\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"background-color: #ffffb3\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color: #e6e6e6;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(1000, 700))
        self.tabWidget.setStyleSheet("QPushButton { color: black; background-color: #f3703c }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.clientIDLabel = QtWidgets.QLabel(self.tab)
        self.clientIDLabel.setObjectName("clientIDLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clientIDLabel)
        self.clientIDLineEdit = QtWidgets.QLineEdit(self.tab)
        self.clientIDLineEdit.setObjectName("clientIDLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clientIDLineEdit)
        self.senderSNameLabel = QtWidgets.QLabel(self.tab)
        self.senderSNameLabel.setObjectName("senderSNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.senderSNameLabel)
        self.senderSNameLineEdit = QtWidgets.QLineEdit(self.tab)
        self.senderSNameLineEdit.setObjectName("senderSNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.senderSNameLineEdit)
        self.pickupAddressLine1Label = QtWidgets.QLabel(self.tab)
        self.pickupAddressLine1Label.setObjectName("pickupAddressLine1Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pickupAddressLine1Label)
        self.pickupAddressLine1LineEdit = QtWidgets.QLineEdit(self.tab)
        self.pickupAddressLine1LineEdit.setObjectName("pickupAddressLine1LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pickupAddressLine1LineEdit)
        self.pickupAddressLine2Label = QtWidgets.QLabel(self.tab)
        self.pickupAddressLine2Label.setObjectName("pickupAddressLine2Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pickupAddressLine2Label)
        self.pickupAddressLine2LineEdit = QtWidgets.QLineEdit(self.tab)
        self.pickupAddressLine2LineEdit.setObjectName("pickupAddressLine2LineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pickupAddressLine2LineEdit)
        self.pickupAddressLine3Label = QtWidgets.QLabel(self.tab)
        self.pickupAddressLine3Label.setObjectName("pickupAddressLine3Label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pickupAddressLine3Label)
        self.pickupAddressLine3LineEdit = QtWidgets.QLineEdit(self.tab)
        self.pickupAddressLine3LineEdit.setObjectName("pickupAddressLine3LineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pickupAddressLine3LineEdit)
        self.pickupCityLabel = QtWidgets.QLabel(self.tab)
        self.pickupCityLabel.setObjectName("pickupCityLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pickupCityLabel)
        self.pickupCityLineEdit = QtWidgets.QLineEdit(self.tab)
        self.pickupCityLineEdit.setObjectName("pickupCityLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pickupCityLineEdit)
        self.pickupProvinceLabel = QtWidgets.QLabel(self.tab)
        self.pickupProvinceLabel.setObjectName("pickupProvinceLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pickupProvinceLabel)
        self.pickupProvinceLineEdit = QtWidgets.QLineEdit(self.tab)
        self.pickupProvinceLineEdit.setObjectName("pickupProvinceLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pickupProvinceLineEdit)
        self.pickupPostalCodeLabel = QtWidgets.QLabel(self.tab)
        self.pickupPostalCodeLabel.setObjectName("pickupPostalCodeLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pickupPostalCodeLabel)
        self.pickupPostalCodeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.pickupPostalCodeLineEdit.setObjectName("pickupPostalCodeLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pickupPostalCodeLineEdit)
        self.recipientSNameLabel = QtWidgets.QLabel(self.tab)
        self.recipientSNameLabel.setObjectName("recipientSNameLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.recipientSNameLabel)
        self.recipientSNameLineEdit = QtWidgets.QLineEdit(self.tab)
        self.recipientSNameLineEdit.setObjectName("recipientSNameLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.recipientSNameLineEdit)
        self.deliveryAddressLine1Label = QtWidgets.QLabel(self.tab)
        self.deliveryAddressLine1Label.setObjectName("deliveryAddressLine1Label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.deliveryAddressLine1Label)
        self.deliveryAddressLine1LineEdit = QtWidgets.QLineEdit(self.tab)
        self.deliveryAddressLine1LineEdit.setObjectName("deliveryAddressLine1LineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.deliveryAddressLine1LineEdit)
        self.deliveryAddressLine2Label = QtWidgets.QLabel(self.tab)
        self.deliveryAddressLine2Label.setObjectName("deliveryAddressLine2Label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.deliveryAddressLine2Label)
        self.deliveryAddressLine2LineEdit = QtWidgets.QLineEdit(self.tab)
        self.deliveryAddressLine2LineEdit.setObjectName("deliveryAddressLine2LineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.deliveryAddressLine2LineEdit)
        self.deliveryAdrressLine3Label = QtWidgets.QLabel(self.tab)
        self.deliveryAdrressLine3Label.setObjectName("deliveryAdrressLine3Label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.deliveryAdrressLine3Label)
        self.deliveryAdrressLine3LineEdit = QtWidgets.QLineEdit(self.tab)
        self.deliveryAdrressLine3LineEdit.setObjectName("deliveryAdrressLine3LineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.deliveryAdrressLine3LineEdit)
        self.deliveryCityLabel = QtWidgets.QLabel(self.tab)
        self.deliveryCityLabel.setObjectName("deliveryCityLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.deliveryCityLabel)
        self.deliveryCityLineEdit = QtWidgets.QLineEdit(self.tab)
        self.deliveryCityLineEdit.setObjectName("deliveryCityLineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.deliveryCityLineEdit)
        self.deliveryProvinceLabel = QtWidgets.QLabel(self.tab)
        self.deliveryProvinceLabel.setObjectName("deliveryProvinceLabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.deliveryProvinceLabel)
        self.deliveryProvinceLineEdit = QtWidgets.QLineEdit(self.tab)
        self.deliveryProvinceLineEdit.setObjectName("deliveryProvinceLineEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.deliveryProvinceLineEdit)
        self.deliveryPostalCodeLabel = QtWidgets.QLabel(self.tab)
        self.deliveryPostalCodeLabel.setObjectName("deliveryPostalCodeLabel")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.deliveryPostalCodeLabel)
        self.deliveryPostalCodeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.deliveryPostalCodeLineEdit.setObjectName("deliveryPostalCodeLineEdit")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.deliveryPostalCodeLineEdit)
        self.deliveryCountryAbreviationLabel = QtWidgets.QLabel(self.tab)
        self.deliveryCountryAbreviationLabel.setObjectName("deliveryCountryAbreviationLabel")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.deliveryCountryAbreviationLabel)
        self.deliveryCountryAbreviationLineEdit = QtWidgets.QLineEdit(self.tab)
        self.deliveryCountryAbreviationLineEdit.setObjectName("deliveryCountryAbreviationLineEdit")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.deliveryCountryAbreviationLineEdit)
        self.uniqueBarcodeOnPkgLabel = QtWidgets.QLabel(self.tab)
        self.uniqueBarcodeOnPkgLabel.setObjectName("uniqueBarcodeOnPkgLabel")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.uniqueBarcodeOnPkgLabel)
        self.uniqueBarcodeOnPkgLineEdit = QtWidgets.QLineEdit(self.tab)
        self.uniqueBarcodeOnPkgLineEdit.setObjectName("uniqueBarcodeOnPkgLineEdit")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.uniqueBarcodeOnPkgLineEdit)
        self.Import = QtWidgets.QPushButton(self.tab)
        self.Import.setMaximumSize(QtCore.QSize(100, 30))
        self.Import.setAutoFillBackground(False)
        self.Import.setStyleSheet("")
        self.Import.setDefault(False)
        self.Import.setFlat(False)
        self.Import.setObjectName("Import")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.Import)
        self.AddRow = QtWidgets.QPushButton(self.tab)
        self.AddRow.setMinimumSize(QtCore.QSize(0, 0))
        self.AddRow.setMaximumSize(QtCore.QSize(100, 30))
        self.AddRow.setStyleSheet("")
        self.AddRow.setObjectName("AddRow")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.AddRow)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(5, -1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.sendersReferenceNumberLabel = QtWidgets.QLabel(self.tab)
        self.sendersReferenceNumberLabel.setObjectName("sendersReferenceNumberLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sendersReferenceNumberLabel)
        self.sendersReferenceNumberLineEdit = QtWidgets.QLineEdit(self.tab)
        self.sendersReferenceNumberLineEdit.setObjectName("sendersReferenceNumberLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sendersReferenceNumberLineEdit)
        self.shipmentReferenceNumberLabel = QtWidgets.QLabel(self.tab)
        self.shipmentReferenceNumberLabel.setObjectName("shipmentReferenceNumberLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.shipmentReferenceNumberLabel)
        self.shipmentReferenceNumberLineEdit = QtWidgets.QLineEdit(self.tab)
        self.shipmentReferenceNumberLineEdit.setObjectName("shipmentReferenceNumberLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shipmentReferenceNumberLineEdit)
        self.pieceNumberForShipmentLabel = QtWidgets.QLabel(self.tab)
        self.pieceNumberForShipmentLabel.setObjectName("pieceNumberForShipmentLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pieceNumberForShipmentLabel)
        self.pieceNumberForShipmentLineEdit = QtWidgets.QLineEdit(self.tab)
        self.pieceNumberForShipmentLineEdit.setObjectName("pieceNumberForShipmentLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pieceNumberForShipmentLineEdit)
        self.pieceWeightLabel = QtWidgets.QLabel(self.tab)
        self.pieceWeightLabel.setObjectName("pieceWeightLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pieceWeightLabel)
        self.pieceWeightLineEdit = QtWidgets.QLineEdit(self.tab)
        self.pieceWeightLineEdit.setObjectName("pieceWeightLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pieceWeightLineEdit)
        self.unitOfMeasurementLabel = QtWidgets.QLabel(self.tab)
        self.unitOfMeasurementLabel.setObjectName("unitOfMeasurementLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.unitOfMeasurementLabel)
        self.unitOfMeasurementLineEdit = QtWidgets.QLineEdit(self.tab)
        self.unitOfMeasurementLineEdit.setObjectName("unitOfMeasurementLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.unitOfMeasurementLineEdit)
        self.specialInstructionsLabel = QtWidgets.QLabel(self.tab)
        self.specialInstructionsLabel.setObjectName("specialInstructionsLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.specialInstructionsLabel)
        self.specialInstructionsLineEdit = QtWidgets.QLineEdit(self.tab)
        self.specialInstructionsLineEdit.setObjectName("specialInstructionsLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.specialInstructionsLineEdit)
        self.serviceTypeLabel = QtWidgets.QLabel(self.tab)
        self.serviceTypeLabel.setObjectName("serviceTypeLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.serviceTypeLabel)
        self.serviceTypeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.serviceTypeLineEdit.setObjectName("serviceTypeLineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.serviceTypeLineEdit)
        self.recipientPhoneNumberLabel = QtWidgets.QLabel(self.tab)
        self.recipientPhoneNumberLabel.setObjectName("recipientPhoneNumberLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.recipientPhoneNumberLabel)
        self.recipientPhoneNumberLineEdit = QtWidgets.QLineEdit(self.tab)
        self.recipientPhoneNumberLineEdit.setObjectName("recipientPhoneNumberLineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.recipientPhoneNumberLineEdit)
        self.recipientEmailAddressLabel = QtWidgets.QLabel(self.tab)
        self.recipientEmailAddressLabel.setObjectName("recipientEmailAddressLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.recipientEmailAddressLabel)
        self.recipientEmailAddressLineEdit = QtWidgets.QLineEdit(self.tab)
        self.recipientEmailAddressLineEdit.setObjectName("recipientEmailAddressLineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.recipientEmailAddressLineEdit)
        self.pickupCountryAbrvLabel = QtWidgets.QLabel(self.tab)
        self.pickupCountryAbrvLabel.setObjectName("pickupCountryAbrvLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pickupCountryAbrvLabel)
        self.pickupCountryAbrvLineEdit = QtWidgets.QLineEdit(self.tab)
        self.pickupCountryAbrvLineEdit.setObjectName("pickupCountryAbrvLineEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pickupCountryAbrvLineEdit)
        self.pieceDescriptionLabel = QtWidgets.QLabel(self.tab)
        self.pieceDescriptionLabel.setObjectName("pieceDescriptionLabel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.pieceDescriptionLabel)
        self.pieceDescriptionLineEdit = QtWidgets.QLineEdit(self.tab)
        self.pieceDescriptionLineEdit.setObjectName("pieceDescriptionLineEdit")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.pieceDescriptionLineEdit)
        self.routeCodeLabel = QtWidgets.QLabel(self.tab)
        self.routeCodeLabel.setObjectName("routeCodeLabel")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.routeCodeLabel)
        self.routeCodeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.routeCodeLineEdit.setObjectName("routeCodeLineEdit")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.routeCodeLineEdit)
        self.senderSPhoneLabel = QtWidgets.QLabel(self.tab)
        self.senderSPhoneLabel.setObjectName("senderSPhoneLabel")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.senderSPhoneLabel)
        self.senderSPhoneLineEdit = QtWidgets.QLineEdit(self.tab)
        self.senderSPhoneLineEdit.setObjectName("senderSPhoneLineEdit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.senderSPhoneLineEdit)
        self.reference3Label = QtWidgets.QLabel(self.tab)
        self.reference3Label.setObjectName("reference3Label")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.reference3Label)
        self.reference3LineEdit = QtWidgets.QLineEdit(self.tab)
        self.reference3LineEdit.setObjectName("reference3LineEdit")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.reference3LineEdit)
        self.reference4Label = QtWidgets.QLabel(self.tab)
        self.reference4Label.setObjectName("reference4Label")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.reference4Label)
        self.reference4LineEdit = QtWidgets.QLineEdit(self.tab)
        self.reference4LineEdit.setObjectName("reference4LineEdit")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.reference4LineEdit)
        self.laborCodeLabel = QtWidgets.QLabel(self.tab)
        self.laborCodeLabel.setObjectName("laborCodeLabel")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.laborCodeLabel)
        self.laborCodeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.laborCodeLineEdit.setObjectName("laborCodeLineEdit")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.laborCodeLineEdit)
        self.jobOptionLabel = QtWidgets.QLabel(self.tab)
        self.jobOptionLabel.setObjectName("jobOptionLabel")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.jobOptionLabel)
        self.jobOptionLineEdit = QtWidgets.QLineEdit(self.tab)
        self.jobOptionLineEdit.setObjectName("jobOptionLineEdit")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.jobOptionLineEdit)
        self.Clear = QtWidgets.QPushButton(self.tab)
        self.Clear.setMaximumSize(QtCore.QSize(100, 30))
        self.Clear.setObjectName("Clear")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.Clear)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(5, -1, -1, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.emailNotificationOptionLabel = QtWidgets.QLabel(self.tab)
        self.emailNotificationOptionLabel.setObjectName("emailNotificationOptionLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.emailNotificationOptionLabel)
        self.EmailNotificationOptionLineEdit = QtWidgets.QLineEdit(self.tab)
        self.EmailNotificationOptionLineEdit.setObjectName("EmailNotificationOptionLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.EmailNotificationOptionLineEdit)
        self.additionalBarcodeLabel = QtWidgets.QLabel(self.tab)
        self.additionalBarcodeLabel.setObjectName("additionalBarcodeLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.additionalBarcodeLabel)
        self.additionalBarcodeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.additionalBarcodeLineEdit.setObjectName("additionalBarcodeLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.additionalBarcodeLineEdit)
        self.massEmailNotificationsLabel = QtWidgets.QLabel(self.tab)
        self.massEmailNotificationsLabel.setObjectName("massEmailNotificationsLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.massEmailNotificationsLabel)
        self.massEmailNotificationsLineEdit = QtWidgets.QLineEdit(self.tab)
        self.massEmailNotificationsLineEdit.setObjectName("massEmailNotificationsLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.massEmailNotificationsLineEdit)
        self.requestedDateTimeLabel = QtWidgets.QLabel(self.tab)
        self.requestedDateTimeLabel.setObjectName("requestedDateTimeLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.requestedDateTimeLabel)
        self.requestedDateTimeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.requestedDateTimeLineEdit.setObjectName("requestedDateTimeLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.requestedDateTimeLineEdit)
        self.specialMobileInstructionsLabel = QtWidgets.QLabel(self.tab)
        self.specialMobileInstructionsLabel.setObjectName("specialMobileInstructionsLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.specialMobileInstructionsLabel)
        self.specialMobileInstructionsLineEdit = QtWidgets.QLineEdit(self.tab)
        self.specialMobileInstructionsLineEdit.setObjectName("specialMobileInstructionsLineEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.specialMobileInstructionsLineEdit)
        self.readyLabel = QtWidgets.QLabel(self.tab)
        self.readyLabel.setObjectName("readyLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.readyLabel)
        self.readyLineEdit = QtWidgets.QLineEdit(self.tab)
        self.readyLineEdit.setObjectName("readyLineEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.readyLineEdit)
        self.lengthLabel = QtWidgets.QLabel(self.tab)
        self.lengthLabel.setObjectName("lengthLabel")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lengthLabel)
        self.lengthLineEdit = QtWidgets.QLineEdit(self.tab)
        self.lengthLineEdit.setObjectName("lengthLineEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lengthLineEdit)
        self.widthLabel = QtWidgets.QLabel(self.tab)
        self.widthLabel.setObjectName("widthLabel")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.widthLabel)
        self.widthLineEdit = QtWidgets.QLineEdit(self.tab)
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.widthLineEdit)
        self.heightLabel = QtWidgets.QLabel(self.tab)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.heightLineEdit = QtWidgets.QLineEdit(self.tab)
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.heightLineEdit)
        self.uOMLengthLabel = QtWidgets.QLabel(self.tab)
        self.uOMLengthLabel.setObjectName("uOMLengthLabel")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.uOMLengthLabel)
        self.uOMLengthLineEdit = QtWidgets.QLineEdit(self.tab)
        self.uOMLengthLineEdit.setObjectName("uOMLengthLineEdit")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.uOMLengthLineEdit)
        self.paymentTypeCodeLabel = QtWidgets.QLabel(self.tab)
        self.paymentTypeCodeLabel.setObjectName("paymentTypeCodeLabel")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.paymentTypeCodeLabel)
        self.paymentTypeCodeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.paymentTypeCodeLineEdit.setObjectName("paymentTypeCodeLineEdit")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.paymentTypeCodeLineEdit)
        self.overridenCostLabel = QtWidgets.QLabel(self.tab)
        self.overridenCostLabel.setObjectName("overridenCostLabel")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.overridenCostLabel)
        self.overridenCostLineEdit = QtWidgets.QLineEdit(self.tab)
        self.overridenCostLineEdit.setObjectName("overridenCostLineEdit")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.overridenCostLineEdit)
        self.jobDescriptionLabel = QtWidgets.QLabel(self.tab)
        self.jobDescriptionLabel.setObjectName("jobDescriptionLabel")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.jobDescriptionLabel)
        self.jobDescriptionLineEdit = QtWidgets.QLineEdit(self.tab)
        self.jobDescriptionLineEdit.setObjectName("jobDescriptionLineEdit")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.jobDescriptionLineEdit)
        self.salesOrderNumberLabel = QtWidgets.QLabel(self.tab)
        self.salesOrderNumberLabel.setObjectName("salesOrderNumberLabel")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.salesOrderNumberLabel)
        self.salesOrderNumberLineEdit = QtWidgets.QLineEdit(self.tab)
        self.salesOrderNumberLineEdit.setObjectName("salesOrderNumberLineEdit")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.salesOrderNumberLineEdit)
        self.secondRouteCodeLabel = QtWidgets.QLabel(self.tab)
        self.secondRouteCodeLabel.setObjectName("secondRouteCodeLabel")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.secondRouteCodeLabel)
        self.secondRouteCodeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.secondRouteCodeLineEdit.setObjectName("secondRouteCodeLineEdit")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.secondRouteCodeLineEdit)
        self.accountNumberLabel = QtWidgets.QLabel(self.tab)
        self.accountNumberLabel.setObjectName("accountNumberLabel")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.accountNumberLabel)
        self.accountNumberLineEdit = QtWidgets.QLineEdit(self.tab)
        self.accountNumberLineEdit.setObjectName("accountNumberLineEdit")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.accountNumberLineEdit)
        self.declaredValueLabel = QtWidgets.QLabel(self.tab)
        self.declaredValueLabel.setObjectName("declaredValueLabel")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.declaredValueLabel)
        self.declaredValueLineEdit = QtWidgets.QLineEdit(self.tab)
        self.declaredValueLineEdit.setObjectName("declaredValueLineEdit")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.declaredValueLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(51)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.RemoveRow = QtWidgets.QPushButton(self.tab_2)
        self.RemoveRow.setMaximumSize(QtCore.QSize(100, 100))
        self.RemoveRow.setObjectName("RemoveRow")
        self.verticalLayout_2.addWidget(self.RemoveRow)
        self.Export = QtWidgets.QPushButton(self.tab_2)
        self.Export.setMaximumSize(QtCore.QSize(100, 100))
        self.Export.setObjectName("Export")
        self.verticalLayout_2.addWidget(self.Export)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clientIDLabel.setText(_translate("MainWindow", "Client ID"))
        self.senderSNameLabel.setText(_translate("MainWindow", "Sender\'s Name"))
        self.pickupAddressLine1Label.setText(_translate("MainWindow", "Pickup Address Line 1"))
        self.pickupAddressLine2Label.setText(_translate("MainWindow", "Pickup Address Line 2"))
        self.pickupAddressLine3Label.setText(_translate("MainWindow", "Pickup Address Line 3"))
        self.pickupCityLabel.setText(_translate("MainWindow", "Pickup City"))
        self.pickupProvinceLabel.setText(_translate("MainWindow", "Pickup Province"))
        self.pickupPostalCodeLabel.setText(_translate("MainWindow", "Pickup Postal Code"))
        self.recipientSNameLabel.setText(_translate("MainWindow", "Recipient\'s Name"))
        self.deliveryAddressLine1Label.setText(_translate("MainWindow", "Delivery Address Line 1"))
        self.deliveryAddressLine2Label.setText(_translate("MainWindow", "Delivery Address Line 2"))
        self.deliveryAdrressLine3Label.setText(_translate("MainWindow", "Delivery Adrress Line 3"))
        self.deliveryCityLabel.setText(_translate("MainWindow", "Delivery City"))
        self.deliveryProvinceLabel.setText(_translate("MainWindow", "Delivery Province"))
        self.deliveryPostalCodeLabel.setText(_translate("MainWindow", "Delivery Postal Code"))
        self.deliveryCountryAbreviationLabel.setText(_translate("MainWindow", "Delivery Country Abr"))
        self.uniqueBarcodeOnPkgLabel.setText(_translate("MainWindow", "Unique Barcode on Pkg"))
        self.Import.setText(_translate("MainWindow", "Import"))
        self.AddRow.setText(_translate("MainWindow", "AddRow"))
        self.sendersReferenceNumberLabel.setText(_translate("MainWindow", "Senders Reference Number"))
        self.shipmentReferenceNumberLabel.setText(_translate("MainWindow", "Shipment Reference Number"))
        self.pieceNumberForShipmentLabel.setText(_translate("MainWindow", "Piece Number for Shipment"))
        self.pieceWeightLabel.setText(_translate("MainWindow", "Piece Weight"))
        self.unitOfMeasurementLabel.setText(_translate("MainWindow", "Unit of Measurement"))
        self.specialInstructionsLabel.setText(_translate("MainWindow", "Special instructions"))
        self.serviceTypeLabel.setText(_translate("MainWindow", "Service Type"))
        self.recipientPhoneNumberLabel.setText(_translate("MainWindow", "Recipient Phone Number"))
        self.recipientEmailAddressLabel.setText(_translate("MainWindow", "Recipient Email Address"))
        self.pickupCountryAbrvLabel.setText(_translate("MainWindow", "Pickup Country Abrv"))
        self.pieceDescriptionLabel.setText(_translate("MainWindow", "Piece Description"))
        self.routeCodeLabel.setText(_translate("MainWindow", "Route Code"))
        self.senderSPhoneLabel.setText(_translate("MainWindow", "Sender\'s Phone"))
        self.reference3Label.setText(_translate("MainWindow", "Reference 3"))
        self.reference4Label.setText(_translate("MainWindow", "Reference 4"))
        self.laborCodeLabel.setText(_translate("MainWindow", "Labor Code"))
        self.jobOptionLabel.setText(_translate("MainWindow", "Job Option"))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.emailNotificationOptionLabel.setText(_translate("MainWindow", "Email Notification Option"))
        self.additionalBarcodeLabel.setText(_translate("MainWindow", "Additional Barcode"))
        self.massEmailNotificationsLabel.setText(_translate("MainWindow", "Mass Email notifications"))
        self.requestedDateTimeLabel.setText(_translate("MainWindow", "Requested Date Time"))
        self.specialMobileInstructionsLabel.setText(_translate("MainWindow", "Special Mobile Instructions"))
        self.readyLabel.setText(_translate("MainWindow", "Ready"))
        self.lengthLabel.setText(_translate("MainWindow", "Length"))
        self.widthLabel.setText(_translate("MainWindow", "Width"))
        self.heightLabel.setText(_translate("MainWindow", "Height"))
        self.uOMLengthLabel.setText(_translate("MainWindow", "UOM Length"))
        self.paymentTypeCodeLabel.setText(_translate("MainWindow", "Payment Type Code"))
        self.overridenCostLabel.setText(_translate("MainWindow", "Overriden Cost"))
        self.jobDescriptionLabel.setText(_translate("MainWindow", "Job Description"))
        self.salesOrderNumberLabel.setText(_translate("MainWindow", "Sales Order Number"))
        self.secondRouteCodeLabel.setText(_translate("MainWindow", "Second Route Code"))
        self.accountNumberLabel.setText(_translate("MainWindow", "Account Number"))
        self.declaredValueLabel.setText(_translate("MainWindow", "Declared Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.RemoveRow.setText(_translate("MainWindow", "Remove Row"))
        self.Export.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

